# Generated by Django 5.1 on 2024-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tariff_unit', models.CharField(max_length=10)),
                ('tariff_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_at', models.DateTimeField()),
                ('last_payment_time', models.DateTimeField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('unpaid_duration', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
